name: Trigger auto deployment for ntfytest

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ntfytest-AutoDeployTrigger-8778b82a-fcdc-4f8b-ae60-265d040c3d84.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.NTFYTEST_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NTFYTEST_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NTFYTEST_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containertest3.azurecr.io
          registryUsername: ${{ secrets.NTFYTEST_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NTFYTEST_REGISTRY_PASSWORD }}
          containerAppName: ntfytest
          resourceGroup: containerapps
          imageToBuild: containertest3.azurecr.io/ntfytest:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


